---
- id: 1
  name: Black
  friendly_id: color__black
  attribute_id: 3
  swatch: "#000000"
- id: 2
  name: Blue
  friendly_id: color__blue
  attribute_id: 3
  swatch: "#0000FF"
- id: 3
  name: White
  friendly_id: color__white
  attribute_id: 3
  swatch: "#FFFFFF"
- id: 4
  name: Gold
  friendly_id: color__gold
  attribute_id: 3
  swatch: "#FFD700"
- id: 5
  name: Silver
  friendly_id: color__silver
  attribute_id: 3
  swatch: "#C0C0C0"
- id: 6
  name: Beige
  friendly_id: color__beige
  attribute_id: 3
  swatch: "#F5F5DC"
- id: 7
  name: Brown
  friendly_id: color__brown
  attribute_id: 3
  swatch: "#A52A2A"
- id: 8
  name: Gray
  friendly_id: color__gray
  attribute_id: 3
  swatch: "#808080"
- id: 9
  name: Green
  friendly_id: color__green
  attribute_id: 3
  swatch: "#008000"
- id: 10
  name: Orange
  friendly_id: color__orange
  attribute_id: 3
  swatch: "#FFA500"
- id: 11
  name: Pink
  friendly_id: color__pink
  attribute_id: 3
  swatch: "#FFC0CB"
- id: 12
  name: Purple
  friendly_id: color__purple
  attribute_id: 3
  swatch: "#800080"
- id: 13
  name: Red
  friendly_id: color__red
  attribute_id: 3
  swatch: "#FF0000"
- id: 14
  name: Yellow
  friendly_id: color__yellow
  attribute_id: 3
  swatch: "#FFFF00"
- id: 15
  name: Navy
  friendly_id: color__navy
  attribute_id: 3
  swatch: "#000080"
- id: 16
  name: Rose gold
  friendly_id: color__rose_gold
  attribute_id: 3
  swatch: "#B76E79"
- id: 17
  name: Clear
  friendly_id: color__clear
  attribute_id: 3
  swatch: "#F5F5F5"
- id: 18
  name: Bronze
  friendly_id: color__bronze
  attribute_id: 3
  swatch: "#CD7F32"
- id: 19
  name: 3XS
  friendly_id: size__triple_extra_small_xxxs
  attribute_id: 1
- id: 20
  name: 2XS
  friendly_id: size__double_extra_small_xxs
  attribute_id: 1
- id: 21
  name: XS
  friendly_id: size__extra_small_xs
  attribute_id: 1
- id: 22
  name: S
  friendly_id: size__small_s
  attribute_id: 1
- id: 23
  name: M
  friendly_id: size__medium_m
  attribute_id: 1
- id: 24
  name: L
  friendly_id: size__large_l
  attribute_id: 1
- id: 25
  name: XL
  friendly_id: size__extra_large_xl
  attribute_id: 1
- id: 26
  name: 2XL
  friendly_id: size__double_extra_large_xxl 
  attribute_id: 1
- id: 27
  name: 3XL
  friendly_id: size__triple_extra_large_xxxl
  attribute_id: 1
- id: 28
  name: 4XL
  friendly_id: size__four_extra_large_4xl
  attribute_id: 1
- id: 29
  name: 5XL
  friendly_id: size__five_extra_large_5xl
  attribute_id: 1
- id: 30
  name: 6XL
  friendly_id: size__six_extra_large_6xl
  attribute_id: 1
- id: 31
  name: '000'
  friendly_id: size__000
  attribute_id: 1
- id: 32
  name: '00'
  friendly_id: size__00
  attribute_id: 1
- id: 33
  name: '0'
  friendly_id: size__0
  attribute_id: 1
- id: 34
  name: '1'
  friendly_id: size__1
  attribute_id: 1
- id: 35
  name: '2'
  friendly_id: size__2
  attribute_id: 1
- id: 36
  name: '4'
  friendly_id: size__4
  attribute_id: 1
- id: 37
  name: '6'
  friendly_id: size__6
  attribute_id: 1
- id: 38
  name: '8'
  friendly_id: size__8
  attribute_id: 1
- id: 39
  name: '10'
  friendly_id: size__10
  attribute_id: 1
- id: 40
  name: '12'
  friendly_id: size__12
  attribute_id: 1
- id: 41
  name: '14'
  friendly_id: size__14
  attribute_id: 1
- id: 42
  name: '16'
  friendly_id: size__16
  attribute_id: 1
- id: 43
  name: '18'
  friendly_id: size__18
  attribute_id: 1
- id: 44
  name: '20'
  friendly_id: size__20
  attribute_id: 1
- id: 45
  name: '22'
  friendly_id: size__22
  attribute_id: 1
- id: 46
  name: '24'
  friendly_id: size__24
  attribute_id: 1
- id: 47
  name: '26'
  friendly_id: size__26
  attribute_id: 1
- id: 48
  name: '28'
  friendly_id: size__28
  attribute_id: 1
- id: 49
  name: '30'
  friendly_id: size__30
  attribute_id: 1
- id: 50
  name: '32'
  friendly_id: size__32
  attribute_id: 1
- id: 51
  name: '34'
  friendly_id: size__34
  attribute_id: 1
- id: 52
  name: '36'
  friendly_id: size__36
  attribute_id: 1
- id: 53
  name: '38'
  friendly_id: size__38
  attribute_id: 1
- id: 54
  name: '40'
  friendly_id: size__40
  attribute_id: 1
- id: 55
  name: '42'
  friendly_id: size__42
  attribute_id: 1
- id: 56
  name: '44'
  friendly_id: size__44
  attribute_id: 1
- id: 57
  name: '46'
  friendly_id: size__46
  attribute_id: 1
- id: 58
  name: '48'
  friendly_id: size__48
  attribute_id: 1
- id: 59
  name: '50'
  friendly_id: size__50
  attribute_id: 1
- id: 60
  name: '52'
  friendly_id: size__52
  attribute_id: 1
- id: 61
  name: '54'
  friendly_id: size__54
  attribute_id: 1
- id: 62
  name: '56'
  friendly_id: size__56
  attribute_id: 1
- id: 63
  name: '58'
  friendly_id: size__58
  attribute_id: 1
- id: 64
  name: '60'
  friendly_id: size__60
  attribute_id: 1
- id: 65
  name: 0-3 months
  friendly_id: size__0_3_months
  attribute_id: 1
- id: 66
  name: 3-6 months
  friendly_id: size__3_6_months
  attribute_id: 1
- id: 67
  name: 6-9 months
  friendly_id: size__6_9_months
  attribute_id: 1
- id: 68
  name: 9-12 months
  friendly_id: size__9_12_months
  attribute_id: 1
- id: 69
  name: 12-18 months
  friendly_id: size__12_18_months
  attribute_id: 1
- id: 70
  name: 18-24 months
  friendly_id: size__18_24_months
  attribute_id: 1
- id: 71
  name: 2-3 years
  friendly_id: size__2_3_years
  attribute_id: 1
- id: 72
  name: 3-4 years
  friendly_id: size__3_4_years  
  attribute_id: 1
- id: 73
  name: 4-5 years
  friendly_id: size__4_5_years
  attribute_id: 1
- id: 74
  name: 5-6 years
  friendly_id: size__5_6_years
  attribute_id: 1
- id: 75
  name: One size
  friendly_id: size__one_size
  attribute_id: 1
- id: 76
  name: Other
  friendly_id: size__other
  attribute_id: 1
- id: 77
  name: 0-6 months
  friendly_id: age_group__0_6_months
  attribute_id: 2
- id: 78
  name: 6-12 months
  friendly_id: age_group__6_12_months
  attribute_id: 2
- id: 79
  name: 1-2 years
  friendly_id: age_group__1_2_years
  attribute_id: 2
- id: 80
  name: Adults
  friendly_id: age_group__adults
  attribute_id: 2
- id: 81
  name: All ages
  friendly_id: age_group__all_ages
  attribute_id: 2
- id: 82
  name: Babies
  friendly_id: age_group__babies
  attribute_id: 2
- id: 83
  name: Kids
  friendly_id: age_group__kids
  attribute_id: 2
- id: 84
  name: Newborns
  friendly_id: age_group__newborn
  attribute_id: 2
- id: 85
  name: Teens
  friendly_id: age_group__teens
  attribute_id: 2
- id: 86
  name: Toddlers
  friendly_id: age_group__toddlers
  attribute_id: 2
- id: 87
  name: Universal
  friendly_id: age_group__universal
  attribute_id: 2
- id: 88
  name: Other
  friendly_id: age_group__other
  attribute_id: 2
- id: 89
  name: Female
  friendly_id: target_gender__female
  attribute_id: 4
- id: 90
  name: Male
  friendly_id: target_gender__male
  attribute_id: 4
- id: 91
  name: Unisex
  friendly_id: target_gender__unisex
  attribute_id: 4
- id: 92
  name: Other
  friendly_id: target_gender__other
  attribute_id: 4
- id: 93
  name: Extra short
  friendly_id: length__extra_short
  attribute_id: 5
- id: 94
  name: Short
  friendly_id: length__short
  attribute_id: 5
- id: 95
  name: Regular
  friendly_id: length__regular
  attribute_id: 5
- id: 96
  name: Long
  friendly_id: length__long
  attribute_id: 5
- id: 97
  name: Extra long
  friendly_id: length__extra_long
  attribute_id: 5
- id: 98
  name: Cropped
  friendly_id: length__cropped
  attribute_id: 5
- id: 99
  name: Ankle
  friendly_id: length__ankle
  attribute_id: 5
- id: 100
  name: Full
  friendly_id: length__full
  attribute_id: 5
- id: 101
  name: Midi
  friendly_id: length__midi
  attribute_id: 5
- id: 102
  name: Maxi
  friendly_id: length__maxi
  attribute_id: 5
- id: 103
  name: Mini
  friendly_id: length__mini
  attribute_id: 5
- id: 104
  name: Knee
  friendly_id: length__knee
  attribute_id: 5
- id: 105
  name: Floor
  friendly_id: length__floor
  attribute_id: 5
- id: 106
  name: '26'
  friendly_id: length__26
  attribute_id: 5
- id: 107
  name: '28'
  friendly_id: length__28
  attribute_id: 5
- id: 108
  name: '30'
  friendly_id: length__30
  attribute_id: 5
- id: 109
  name: '32'
  friendly_id: length__32
  attribute_id: 5
- id: 110
  name: '34'
  friendly_id: length__34
  attribute_id: 5
- id: 111
  name: '36'
  friendly_id: length__36
  attribute_id: 5
- id: 112
  name: '38'
  friendly_id: length__38
  attribute_id: 5
- id: 113
  name: Other
  friendly_id: length__other
  attribute_id: 5
- id: 114
  name: Extra narrow
  friendly_id: width__extra_narrow
  attribute_id: 6
- id: 115
  name: Narrow
  friendly_id: width__narrow
  attribute_id: 6
- id: 116
  name: Medium
  friendly_id: width__medium
  attribute_id: 6
- id: 117
  name: Regular
  friendly_id: width__regular
  attribute_id: 6
- id: 118
  name: Wide
  friendly_id: width__wide
  attribute_id: 6
- id: 119
  name: Extra wide
  friendly_id: width__extra_wide
  attribute_id: 6
- id: 120
  name: Double wide
  friendly_id: width__double_wide
  attribute_id: 6
- id: 121
  name: Other
  friendly_id: width__other
  attribute_id: 6
- id: 122
  name: AA
  friendly_id: cup_size__aa
  attribute_id: 7
- id: 123
  name: A
  friendly_id: cup_size__a
  attribute_id: 7
- id: 124
  name: B
  friendly_id: cup_size__b
  attribute_id: 7
- id: 125
  name: C
  friendly_id: cup_size__c
  attribute_id: 7
- id: 126
  name: D
  friendly_id: cup_size__d
  attribute_id: 7
- id: 127
  name: DD/E
  friendly_id: cup_size__dd_e
  attribute_id: 7
- id: 128
  name: DDD/F
  friendly_id: cup_size__ddd_f
  attribute_id: 7
- id: 129
  name: G
  friendly_id: cup_size__g
  attribute_id: 7
- id: 130
  name: H
  friendly_id: cup_size__h
  attribute_id: 7
- id: 131
  name: I
  friendly_id: cup_size__i
  attribute_id: 7
- id: 132
  name: J
  friendly_id: cup_size__j
  attribute_id: 7
- id: 133
  name: K
  friendly_id: cup_size__k
  attribute_id: 7
- id: 134
  name: Other
  friendly_id: cup_size__other
  attribute_id: 7
- id: 135
  name: '28'
  friendly_id: band_size__28
  attribute_id: 8
- id: 136
  name: '30'
  friendly_id: band_size__30
  attribute_id: 8
- id: 137
  name: '32'
  friendly_id: band_size__32
  attribute_id: 8
- id: 138
  name: '34'
  friendly_id: band_size__34
  attribute_id: 8
- id: 139
  name: '36'
  friendly_id: band_size__36
  attribute_id: 8
- id: 140
  name: '38'
  friendly_id: band_size__38
  attribute_id: 8
- id: 141
  name: '40'
  friendly_id: band_size__40
  attribute_id: 8
- id: 142
  name: '42'
  friendly_id: band_size__42
  attribute_id: 8
- id: 143
  name: '44'
  friendly_id: band_size__44
  attribute_id: 8
- id: 144
  name: '46'
  friendly_id: band_size__46
  attribute_id: 8
- id: 145
  name: '48'
  friendly_id: band_size__48
  attribute_id: 8
- id: 146
  name: '50'
  friendly_id: band_size__50
  attribute_id: 8
- id: 147
  name: Other
  friendly_id: band_size__other
  attribute_id: 8
- id: 148
  name: Acrylic
  friendly_id: fabric__acrylic
  attribute_id: 9
- id: 149
  name: Bamboo
  friendly_id: fabric__bamboo
  attribute_id: 9
- id: 150
  name: Canvas
  friendly_id: fabric__canvas
  attribute_id: 9
- id: 151
  name: Cashmere
  friendly_id: fabric__cashmere
  attribute_id: 9
- id: 152
  name: Chiffon
  friendly_id: fabric__chiffon
  attribute_id: 9
- id: 153
  name: Corduroy
  friendly_id: fabric__corduroy
  attribute_id: 9
- id: 154
  name: Cotton
  friendly_id: fabric__cotton
  attribute_id: 9
- id: 155
  name: Denim
  friendly_id: fabric__denim
  attribute_id: 9
- id: 156
  name: Down
  friendly_id: fabric__down
  attribute_id: 9
- id: 157
  name: Elastane
  friendly_id: fabric__elastane
  attribute_id: 9
- id: 158
  name: Faux fur
  friendly_id: fabric__faux_fur
  attribute_id: 9
- id: 159
  name: Faux leather
  friendly_id: fabric__faux_leather
  attribute_id: 9
- id: 160
  name: Felt
  friendly_id: fabric__felt
  attribute_id: 9
- id: 161
  name: Flannel
  friendly_id: fabric__flannel
  attribute_id: 9
- id: 162
  name: Fleece
  friendly_id: fabric__fleece
  attribute_id: 9
- id: 163
  name: Fur
  friendly_id: fabric__fur
  attribute_id: 9
- id: 164
  name: Gore-Tex
  friendly_id: fabric__gore_tex
  attribute_id: 9
- id: 165
  name: Jersey
  friendly_id: fabric__jersey
  attribute_id: 9
- id: 166
  name: Lace
  friendly_id: fabric__lace
  attribute_id: 9
- id: 167
  name: Leather
  friendly_id: fabric__leather
  attribute_id: 9
- id: 168
  name: Linen
  friendly_id: fabric__linen
  attribute_id: 9
- id: 169
  name: Lyocell
  friendly_id: fabric__lyocell
  attribute_id: 9
- id: 170
  name: Merino wool
  friendly_id: fabric__merino_wool
  attribute_id: 9
- id: 171
  name: Mesh
  friendly_id: fabric__mesh
  attribute_id: 9
- id: 172
  name: Modal
  friendly_id: fabric__modal
  attribute_id: 9
- id: 173
  name: Neoprene
  friendly_id: fabric__neoprene
  attribute_id: 9
- id: 174
  name: Nylon
  friendly_id: fabric__nylon
  attribute_id: 9
- id: 175
  name: Organic cotton
  friendly_id: fabric__organic_cotton
  attribute_id: 9
- id: 176
  name: Polyester
  friendly_id: fabric__polyester
  attribute_id: 9
- id: 177
  name: Rayon
  friendly_id: fabric__rayon
  attribute_id: 9
- id: 178
  name: Recycled polyester
  friendly_id: fabric__recycled_polyester
  attribute_id: 9
- id: 179
  name: Satin
  friendly_id: fabric__satin
  attribute_id: 9
- id: 180
  name: Sequin
  friendly_id: fabric__sequin
  attribute_id: 9
- id: 181
  name: Silk
  friendly_id: fabric__silk
  attribute_id: 9
- id: 182
  name: Spandex
  friendly_id: fabric__spandex
  attribute_id: 9
- id: 183
  name: Suede
  friendly_id: fabric__suede
  attribute_id: 9
- id: 184
  name: Tencel
  friendly_id: fabric__tencel
  attribute_id: 9
- id: 185
  name: Terry
  friendly_id: fabric__terry
  attribute_id: 9
- id: 186
  name: Tulle
  friendly_id: fabric__tulle
  attribute_id: 9
- id: 187
  name: Tweed
  friendly_id: fabric__tweed
  attribute_id: 9
- id: 188
  name: Twill
  friendly_id: fabric__twill
  attribute_id: 9
- id: 189
  name: Velvet
  friendly_id: fabric__velvet
  attribute_id: 9
- id: 190
  name: Viscose
  friendly_id: fabric__viscose
  attribute_id: 9
- id: 191
  name: Wool
  friendly_id: fabric__wool
  attribute_id: 9
- id: 192
  name: Other
  friendly_id: fabric__other
  attribute_id: 9
- id: 193
  name: Abstract
  friendly_id: pattern__abstract
  attribute_id: 10
- id: 194
  name: Animal print
  friendly_id: pattern__animal_print
  attribute_id: 10
- id: 195
  name: Argyle
  friendly_id: pattern__argyle
  attribute_id: 10
- id: 196
  name: Camouflage
  friendly_id: pattern__camouflage
  attribute_id: 10
- id: 197
  name: Checkered
  friendly_id: pattern__checkered
  attribute_id: 10
- id: 198
  name: Chevron
  friendly_id: pattern__chevron
  attribute_id: 10
- id: 199
  name: Color block
  friendly_id: pattern__color_block
  attribute_id: 10
- id: 200
  name: Damask
  friendly_id: pattern__damask
  attribute_id: 10
- id: 201
  name: Distressed
  friendly_id: pattern__distressed
  attribute_id: 10
- id: 202
  name: Dotted
  friendly_id: pattern__dotted
  attribute_id: 10
- id: 203
  name: Embroidered
  friendly_id: pattern__embroidered
  attribute_id: 10
- id: 204
  name: Floral
  friendly_id: pattern__floral
  attribute_id: 10
- id: 205
  name: Geometric
  friendly_id: pattern__geometric
  attribute_id: 10
- id: 206
  name: Gingham
  friendly_id: pattern__gingham
  attribute_id: 10
- id: 207
  name: Gradient
  friendly_id: pattern__gradient
  attribute_id: 10
- id: 208
  name: Graphic
  friendly_id: pattern__graphic
  attribute_id: 10
- id: 209
  name: Herringbone
  friendly_id: pattern__herringbone
  attribute_id: 10
- id: 210
  name: Houndstooth
  friendly_id: pattern__houndstooth
  attribute_id: 10
- id: 211
  name: Ikat
  friendly_id: pattern__ikat
  attribute_id: 10
- id: 212
  name: Leopard
  friendly_id: pattern__leopard
  attribute_id: 10
- id: 213
  name: Marble
  friendly_id: pattern__marble
  attribute_id: 10
- id: 214
  name: Medallion
  friendly_id: pattern__medallion
  attribute_id: 10
- id: 215
  name: Paisley
  friendly_id: pattern__paisley
  attribute_id: 10
- id: 216
  name: Pinstripe
  friendly_id: pattern__pinstripe
  attribute_id: 10
- id: 217
  name: Plaid
  friendly_id: pattern__plaid
  attribute_id: 10
- id: 218
  name: Polka dot
  friendly_id: pattern__polka_dot
  attribute_id: 10
- id: 219
  name: Printed
  friendly_id: pattern__printed
  attribute_id: 10
- id: 220
  name: Quilted
  friendly_id: pattern__quilted
  attribute_id: 10
- id: 221
  name: Snakeskin
  friendly_id: pattern__snakeskin
  attribute_id: 10
- id: 222
  name: Solid
  friendly_id: pattern__solid
  attribute_id: 10
- id: 223
  name: Striped
  friendly_id: pattern__striped
  attribute_id: 10
- id: 224
  name: Tartan
  friendly_id: pattern__tartan
  attribute_id: 10
- id: 225
  name: Tie dye
  friendly_id: pattern__tie_dye
  attribute_id: 10
- id: 226
  name: Toile
  friendly_id: pattern__toile
  attribute_id: 10
- id: 227
  name: Tropical
  friendly_id: pattern__tropical
  attribute_id: 10
- id: 228
  name: Zebra
  friendly_id: pattern__zebra
  attribute_id: 10
- id: 229
  name: Other
  friendly_id: pattern__other
  attribute_id: 10
- id: 230
  name: Extra slim
  friendly_id: fit__extra_slim
  attribute_id: 11
- id: 231
  name: Slim
  friendly_id: fit__slim
  attribute_id: 11
- id: 232
  name: Skinny
  friendly_id: fit__skinny
  attribute_id: 11
- id: 233
  name: Tailored
  friendly_id: fit__tailored
  attribute_id: 11
- id: 234
  name: Regular
  friendly_id: fit__regular
  attribute_id: 11
- id: 235
  name: Classic
  friendly_id: fit__classic
  attribute_id: 11
- id: 236
  name: Straight
  friendly_id: fit__straight
  attribute_id: 11
- id: 237
  name: Relaxed
  friendly_id: fit__relaxed
  attribute_id: 11
- id: 238
  name: Loose
  friendly_id: fit__loose
  attribute_id: 11
- id: 239
  name: Oversized
  friendly_id: fit__oversized
  attribute_id: 11
- id: 240
  name: Boyfriend
  friendly_id: fit__boyfriend
  attribute_id: 11
- id: 241
  name: Girlfriend
  friendly_id: fit__girlfriend
  attribute_id: 11
- id: 242
  name: Mom
  friendly_id: fit__mom
  attribute_id: 11
- id: 243
  name: Dad
  friendly_id: fit__dad
  attribute_id: 11
- id: 244
  name: Athletic
  friendly_id: fit__athletic
  attribute_id: 11
- id: 245
  name: Compression
  friendly_id: fit__compression
  attribute_id: 11
- id: 246
  name: Bootcut
  friendly_id: fit__bootcut
  attribute_id: 11
- id: 247
  name: Flare
  friendly_id: fit__flare
  attribute_id: 11
- id: 248
  name: Wide leg
  friendly_id: fit__wide_leg
  attribute_id: 11
- id: 249
  name: Tapered
  friendly_id: fit__tapered
  attribute_id: 11
- id: 250
  name: Carrot
  friendly_id: fit__carrot
  attribute_id: 11
- id: 251
  name: Baggy
  friendly_id: fit__baggy
  attribute_id: 11
- id: 252
  name: Cropped
  friendly_id: fit__cropped
  attribute_id: 11
- id: 253
  name: High rise
  friendly_id: fit__high_rise
  attribute_id: 11
- id: 254
  name: Mid rise
  friendly_id: fit__mid_rise
  attribute_id: 11
- id: 255
  name: Low rise
  friendly_id: fit__low_rise
  attribute_id: 11
- id: 256
  name: Other
  friendly_id: fit__other
  attribute_id: 11