primary_region = 'ams'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  ALLOWED_API_ORIGINS = 'https://app.avelero.com,http://localhost:3000,https://avelero-app-preview-9215.vercel.app,https://avelero.vercel.app,https://avelero-staging.vercel.app'

[http_service]
  internal_port = 3000
